### PR TITLE
Update for libsemigroups 0.3.2

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Travis has been waiting to run the build for about 24 hours, anyone have any idea what's up?

**Comment by james-d-mitchell** [comment]
@isuruf any suggestions?

**Comment by isuruf** [comment]
@james-d-mitchell, there was an error with the anaconda token which has now been fixed. You'll have to restart the following builds though,
https://travis-ci.org/conda-forge/libsemigroups-feedstock/builds/268133579
https://circleci.com/gh/conda-forge/libsemigroups-feedstock/9

**Comment by james-d-mitchell** [comment]
Thanks @isuruf! I merged it already, since at some point the build was showing as "pass all checks".

**Pull request merged**
