### PR TITLE
Update for libsemigroups 0.3.0

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@isuruf do I need to anything further to update this? Thanks!

**Comment by isuruf** [comment]
+1 to merge

**Comment by isuruf** [comment]
Is the license file still missing in the tarball?

**Comment by james-d-mitchell** [comment]
No it's there now

**Comment by james-d-mitchell** [comment]
Thanks! Do I merge it?

**Comment by isuruf** [comment]
Can you uncomment the line 39 of meta.yaml?

**Comment by james-d-mitchell** [comment]
Done

**Comment by isuruf** [comment]
Thanks. You can merge now

**Comment by james-d-mitchell** [comment]
Great! Thanks for your help!

**Pull request merged**
