### PR TITLE
Update for v1.0.5

### PR DESCRIPTION
**Pull request by james-d-mitchell**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@isuruf any ideas why this is failing??

**Comment by james-d-mitchell** [comment]
Better but still failing, any further ideas @isuruf?

**Comment by james-d-mitchell** [comment]
@isuruf it looks like tests are enabled for aarch and ppc64le,  but that the conda feedstock for `fmt` does not support these architectures, which is why the tests are failing.

**Comment by isuruf** [comment]
We can merge as is for now and figure out aarch64 and ppc64le later.

**Comment by james-d-mitchell** [comment]
Ok thanks, let me drop my last two commits before merging.

**Pull request merged**
