### PR TITLE
Update for v0.6.2

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
@isuruf do you know if it is possible to specify the compiler required by circleci? I'd like to use GCC 5 instead of GCC 4.8.  If it's not possible, no worries.

**Comment by isuruf** [comment]
Not yet. We are working on moving to `conda-build=3` which comes with newer compiler support.

**Comment by james-d-mitchell** [comment]
@isuruf thanks! Looking forward to the forthcoming changes.

**Comment by james-d-mitchell** [comment]
@isuruf Any idea what's going on with travis? It's just sitting on yellow (no build started) for days now.

**Comment by isuruf** [comment]
There were issues in travis-ci side for about a week and now those are fixed on their side, but there is a huge queue because of that.

**Comment by james-d-mitchell** [comment]
Thanks I'll keep waiting then!

**Pull request merged**
