### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by james-d-mitchell**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
The link:

https://conda-forge.org/docs/conda_smithy.html#how-to-re-render 

is broken, I tried linting `meta.yml` with `conda smithy` as indicated above, but I get:
~~~~
Traceback (most recent call last):
  File "/Users/jdm/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/jdm/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 489, in main
    args.subcommand_func(args)
  File "/Users/jdm/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 384, in __call__
    return_hints=True,
  File "/Users/jdm/miniconda3/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 689, in main
    results, hints = lintify(meta, recipe_dir, conda_forge)
  File "/Users/jdm/miniconda3/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 462, in lintify
    for req in host_reqs
TypeError: 'NoneType' object is not iterable
~~~~

I tried rerendering using the instructions above and got an email:

~~~~
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like I wasn't able to push to the v1.0.0 branch of libsemigroups/libsemigroups-feedstock. Did you check the "Allow edits from maintainers" box?

~~~~
Although the "Allow edits form maintainers" box is checked, it seems to want to push branch v1.0.0.

**Comment by james-d-mitchell** [comment]
@conda-forge-admin, please rerender

**Comment by james-d-mitchell** [comment]
Nothing is working :( @isuruf any hints?

**Comment by isuruf** [comment]
Opened https://github.com/libsemigroups/libsemigroups/issues/131 for the macOS issue

**Comment by james-d-mitchell** [comment]
Thanks @isuruf I’ll fix that tomorrow, any idea what’s wrong with the meta.yml file?

**Comment by isuruf** [comment]
Which conda-smithy version did you use?

**Comment by james-d-mitchell** [comment]
I’ll have to check tomorrow, but I freshly installed conda smithy today using conda, so it should be up to date.

**Comment by james-d-mitchell** [comment]
I'm using version 3.6.3 of conda smithy

**Comment by james-d-mitchell** [comment]
I made another release that hopefully fixes the osx issue, I opened a new PR for that #23. 

I still have no idea what's wrong with the `meta.yml` file, any hints gratefully received!

**Pull request closed without merging**
